/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Robot;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception{
        System.out.println("MouseJiggler app initiated");
        Robot robot = new Robot();
        while(true) {
        	Point point = MouseInfo.getPointerInfo().getLocation();
        	robot.mouseMove(point.x, point.y);
        	Thread.sleep(1000);
        }
    }
}
